### ISSUE TITLE
Totally remove and reinstall?

### ISSUE THREAD

**Issue by therealcyber5** [wwmm/pulseeffects#138]
How do I totally remove this from Ubuntu 17.10 and reinstall the latest build? I tried to install from source and it fires up visually throwing these errors to my Terminal window:

** (pulseeffects:14780): CRITICAL **: gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed
20:06:03.344 - PulseEffects - ERROR - (gerror=GLib.Error('Internal data stream error.', 'gst-stream-error-quark', 1), debug='gstbasesrc.c(2939): gst_base_src_loop (): /GstPipeline:pipeline0/GstPulseSrc:audio_src:\nstreaming stopped, reason error (-5)')
20:06:03.346 - PulseEffects - INFO - pipeline state: null
20:06:03.350 - PulseEffects - INFO - pipeline state: playing

** (pulseeffects:14780): CRITICAL **: gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed
20:06:03.431 - PulseEffects - INFO - pulsesrc latency-time [us]: 5000
20:06:03.431 - PulseEffects - INFO - pulsesrc buffer-time [us]: 100000
20:06:03.431 - PulseEffects - INFO - pulsesink latency-time [us]: 5000
20:06:03.431 - PulseEffects - INFO - pulsesink buffer-time [us]: 100000
20:06:03.431 - PulseEffects - ERROR - (gerror=GLib.Error('Internal data stream error.', 'gst-stream-error-quark', 1), debug='gstbasesrc.c(2939): gst_base_src_loop (): /GstPipeline:pipeline0/GstPulseSrc:audio_src:\nstreaming stopped, reason error (-5)')
20:06:03.432 - PulseEffects - INFO - pipeline state: null
20:06:03.436 - PulseEffects - INFO - pipeline state: playing
20:06:03.438 - PulseEffects - INFO - pulsesrc latency-time [us]: 5000
20:06:03.438 - PulseEffects - INFO - pulsesrc buffer-time [us]: 100000
20:06:03.441 - PulseEffects - INFO - pulsesink latency-time [us]: 5000
20:06:03.441 - PulseEffects - INFO - pulsesink buffer-time [us]: 100000

** (pulseeffects:14780): CRITICAL **: gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed
20:06:03.485 - PulseEffects - INFO - pipeline state: null
20:06:03.486 - PulseEffects - INFO - pipeline state: null
20:06:03.486 - PulseEffects - INFO - sinks unloaded
20:06:03.486 - PulseEffects - INFO - disconnecting pulseaudio context
20:06:03.486 - PulseEffects - INFO - pulseaudio context terminated
20:06:03.486 - PulseEffects - INFO - unferencing pulseaudio context object
20:06:03.486 - PulseEffects - INFO - stopping pulseaudio threaded main loop
20:06:03.486 - PulseEffects - INFO - freeing pulseaudio main loop object

/var/syslog goes crazy - here's a sample from that file:
76 - PulseEffects - INFO - pulsesink latency-time [us]: 5000
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.276 - PulseEffects - INFO - pulsesink buffer-time [us]: 100000
Dec 12 20:08:35 MtOlympus python3[17854]: gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.305 - PulseEffects - ERROR - (gerror=GLib.Error('Internal data stream error.', 'gst-stream-error-quark', 1), debug='gstbasesrc.c(2939): gst_base_src_loop (): /GstPipeline:pipeline0/GstPulseSrc:audio_src:\nstreaming stopped, reason error (-5)')
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.308 - PulseEffects - INFO - pipeline state: null
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.312 - PulseEffects - INFO - pipeline state: playing
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.313 - PulseEffects - INFO - pulsesrc latency-time [us]: 5000
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.314 - PulseEffects - INFO - pulsesrc buffer-time [us]: 100000
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.315 - PulseEffects - INFO - pulsesink latency-time [us]: 5000
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.315 - PulseEffects - INFO - pulsesink buffer-time [us]: 100000
Dec 12 20:08:35 MtOlympus python3[17854]: gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.387 - PulseEffects - INFO - pipeline state: null
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.387 - PulseEffects - INFO - pipeline state: null
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.387 - PulseEffects - INFO - sinks unloaded
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.387 - PulseEffects - INFO - disconnecting pulseaudio context
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.387 - PulseEffects - INFO - pulseaudio context terminated
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.387 - PulseEffects - INFO - unferencing pulseaudio context object
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: 20:08:35.387 - PulseEffects - INFO - stream for sink input 2023 was terminated
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: Assertion '!q->back' failed at pulsecore/queue.c:62, function pa_queue_free(). Aborting.

Sorry, I'm new to linux!
Thanks for what seems like a very cool tool once I know what I'm doing with upgrading software in this OS!

**Comment by wwmm** [comment]
Which commands did you use to install? If you installed from the sources following the instructions in the wiki [https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source](https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source) you can do this to uninstall:

```
cd _build
sudo make uninstall
```

If you are new to linux I would recommend you to either use a package in a third party repository [https://github.com/wwmm/pulseeffects/wiki/Package-Repositories](https://github.com/wwmm/pulseeffects/wiki/Package-Repositories) or to run PulseEffects directly from the sources [https://github.com/wwmm/pulseeffects/wiki/Run-Directly-from-Repository](https://github.com/wwmm/pulseeffects/wiki/Run-Directly-from-Repository).

**Comment by therealcyber5** [comment]
Well, I installed the Ubuntu version from the 3rd party repository but it was the version with 15 frequencies, so I ran the install as per Installation From Source...but since the directory was already there, it failed when I tried to clone the git so I used

`git pull origin master`

 from the pulseeffects directory. 

I do not have a _build directory that I can find but if I run
` sudo ninja uninstall` 
from the directory it is installed in I get
cannot access '_build': No such file or directory

**Comment by therealcyber5** [comment]
`dpkg --list`

shows these pulse audio files installed

ii  pulseaudio     1:10.0-2ubun amd64        PulseAudio sound server
ii  pulseaudio-equ 1:10.0-2ubun amd64        Equalizer sink module for PulseAu
ii  pulseaudio-mod 1:10.0-2ubun amd64        Bluetooth module for PulseAudio s
ii  pulseaudio-uti 1:10.0-2ubun amd64        Command line tools for the PulseA
ii  pulseeffects   3.0.7.3      amd64        Sound input and outout effects fo
ii  pulseeffects-b 3.0.7.3      all          build-dependencies for pulseeffec

can I use sudo `apt-get --purge remove <program>` to uninstall them, remove the directory and start fresh?

**Comment by mikhailnov** [comment]
> Well, I installed the Ubuntu version from the 3rd party repository but it was the version with 15 frequencies
What do you mean under '15 frequencies'? i've just updated pulseeffects in that repository.

Probably ```sudo apt purge pulseeffects``` before installing from source.

**Comment by therealcyber5** [comment]
mikhailnov: I installed it from your repository about 5 hours ago - it had 15 bands in the EQ, not the 30 shown in the images. It appears as if what is on my system currently (which is causing the issues due to the way I tried to install from source) is 3.0.7.3 - I tried overwriting that with 3.1.2 with the source files. Hence, my predicament

**Comment by mikhailnov** [comment]
try updating it,  i've just pushed 3.1.2 into the repo

**Comment by mikhailnov** [comment]
If you have built the **deb** package from source, ```dpkg -l``` will show 3.0.7.3 even if it is actually 3.1.2+newest Git, because you did not manually update the version in ```debian/changelog``` before running ```debuild```.

**Comment by therealcyber5** [comment]
should i remove it first or just install it from your repo to update it?

**Comment by mikhailnov** [comment]
If you followed instructions for Ubuntu in https://github.com/wwmm/pulseeffects/wiki/Installation-from-Source and ran ```debuild -i -us -uc```, than you can just run ```sudo apt update; sudo apt install pulseeffects```, and the newer version will be installed from the repository.

If you installed it from source in another way, than it will probably be better to remove it first.

**Comment by therealcyber5** [comment]
Ok, I removed it and reinstalled it via 
```
wget -q -O- http://repo.dumalogiya.ru/keys/mikhailnov_pub.gpg | sudo apt-key add -
echo "deb http://repo.dumalogiya.ru/aptly/public artful main" | sudo tee /etc/apt/sources.list.d/dumalogiya-artful.list
sudo apt update
sudo apt install pulseeffects
```
and the original problem persists: this is what shows up from my terminal window:
** (pulseeffects:26514): CRITICAL **: gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed
22:12:50.123 - PulseEffects - INFO - pipeline state: null
22:12:50.123 - PulseEffects - INFO - pipeline state: null
22:12:50.123 - PulseEffects - INFO - sinks unloaded
22:12:50.123 - PulseEffects - INFO - disconnecting pulseaudio context
22:12:50.123 - PulseEffects - INFO - pulseaudio context terminated
22:12:50.123 - PulseEffects - INFO - unferencing pulseaudio context object
22:12:50.123 - PulseEffects - INFO - stopping pulseaudio threaded main loop
22:12:50.123 - PulseEffects - INFO - freeing pulseaudio main loop object

**Comment by therealcyber5** [comment]
above that I get 
** (pulseeffects:26514): CRITICAL **: gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed
22:12:50.70 - PulseEffects - ERROR - (gerror=GLib.Error('Internal data stream error.', 'gst-stream-error-quark', 1), debug='gstbasesrc.c(2939): gst_base_src_loop (): /GstPipeline:pipeline0/GstPulseSrc:audio_src:\nstreaming stopped, reason error (-5)')
22:12:50.71 - PulseEffects - INFO - pipeline state: null
22:12:50.75 - PulseEffects - INFO - pipeline state: playing
22:12:50.77 - PulseEffects - INFO - pulsesrc latency-time [us]: 5000
22:12:50.78 - PulseEffects - INFO - pulsesrc buffer-time [us]: 100000
22:12:50.80 - PulseEffects - INFO - pulsesink latency-time [us]: 5000
22:12:50.80 - PulseEffects - INFO - pulsesink buffer-time [us]: 100000

and var/syslog just scrolls errors until I close it

**Comment by mikhailnov** [comment]
the only things that may be a problem are
```** (pulseeffects:26514): CRITICAL **: gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed
Dec 12 20:08:35 MtOlympus com.github.wwmm.pulseeffects.desktop[17854]: Assertion '!q->back' failed at pulsecore/queue.c:62, function pa_queue_free(). Aborting.
```
all the rest are just INFO (not errors) console messages.

It seems to have already been discussed in https://github.com/wwmm/pulseeffects/issues/63

**Comment by mikhailnov** [comment]
Unlike Windows, it is good practice in Linux to print what the program is doing into the console to make debugging problems a lot easier.

**Comment by therealcyber5** [comment]
I get that - but should it be writing 100+ messages per second to var/log/syslog constantly?

This is just a small portion of the log file it generated under a second
Dec 12 22:22:23 MtOlympus python3[27382]: gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed
Dec 12 22:22:23 MtOlympus com.github.wwmm.pulseeffects.desktop[27382]: 22:22:23.923 - PulseEffects - ERROR - (gerror=GLib.Error('Internal data stream error.', 'gst-stream-error-quark', 1), debug='gstbasesrc.c(2939): gst_base_src_loop (): /GstPipeline:pipeline0/GstPulseSrc:audio_src:\nstreaming stopped, reason error (-5)')
Dec 12 22:22:23 MtOlympus com.github.wwmm.pulseeffects.desktop[27382]: 22:22:23.925 - PulseEffects - INFO - pipeline state: null
Dec 12 22:22:23 MtOlympus com.github.wwmm.pulseeffects.desktop[27382]: 22:22:23.930 - PulseEffects - INFO - pipeline state: playing
Dec 12 22:22:23 MtOlympus com.github.wwmm.pulseeffects.desktop[27382]: 22:22:23.932 - PulseEffects - INFO - pulsesrc latency-time [us]: 5000
Dec 12 22:22:23 MtOlympus com.github.wwmm.pulseeffects.desktop[27382]: 22:22:23.932 - PulseEffects - INFO - pulsesrc buffer-time [us]: 100000
Dec 12 22:22:23 MtOlympus com.github.wwmm.pulseeffects.desktop[27382]: 22:22:23.934 - PulseEffects - INFO - pulsesink latency-time [us]: 5000
Dec 12 22:22:23 MtOlympus com.github.wwmm.pulseeffects.desktop[27382]: 22:22:23.934 - PulseEffects - INFO - pulsesink buffer-time [us]: 100000
Dec 12 22:22:23 MtOlympus python3[27382]: gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed

**Comment by mikhailnov** [comment]
On my system it nothing from PulseEffects is written to ```/var/log/syslog``` , 
![deepinscreenshot_select-area_20171213083158](https://user-images.githubusercontent.com/15802528/33923077-1aababbc-dfe0-11e7-9ce0-cc7214bc8988.png)
there are 2 variants:
1. either you changed logging configuration manually
2. or the logging of INFO messages is for some reason started after the error 
``` Dec 12 22:22:23 MtOlympus com.github.wwmm.pulseeffects.desktop[27382]: 22:22:23.923 - PulseEffects - ERROR - (gerror=GLib.Error('Internal data stream error.', 'gst-stream-error-quark', 1), debug='gstbasesrc.c(2939): gst_base_src_loop (): /GstPipeline:pipeline0/GstPulseSrc:audio_src:\nstreaming stopped, reason error (-5)') ```
occurs.

**Comment by therealcyber5** [comment]
Now, when I open it, the EQ has no effect on audio and the window closes almost immediately and syslog shows
Dec 12 22:30:26 MtOlympus com.github.wwmm.pulseeffects.desktop[16537]: **
Dec 12 22:30:26 MtOlympus com.github.wwmm.pulseeffects.desktop[16537]: ERROR:gstspectrum.c:991:gst_spectrum_transform_ip: assertion failed: (size == 0)

**Comment by mikhailnov** [comment]
Do you have anything in syslog if you start  PulseEffects with all applications and effects disabled?

**Comment by mikhailnov** [comment]
``` rm -fvr ~/.config/PulseEffects ``` (NOT under root) will reset all the settings.

**Comment by therealcyber5** [comment]
It closes immediately upon opening now. Syslog shows this with no options enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.362 - PulseEffects - INFO - pulseaudio context started
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.373 - PulseEffects - INFO - connected to server: unix:/run/user/1000/pulse/native
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.383 - PulseEffects - INFO - server protocol version: 32
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.394 - PulseEffects - INFO - pulseaudio version: 10.0
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.394 - PulseEffects - INFO - default pulseaudio source: alsa_output.pci-0000_23_00.1.hdmi-stereo-extra1.monitor
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.394 - PulseEffects - INFO - default pulseaudio sink: PulseEffects_mic
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.395 - PulseEffects - INFO - default pulseaudio sink audio format: s16le
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.395 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.395 - PulseEffects - INFO - default pulseaudio source audio format: s16le
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.395 - PulseEffects - INFO - default pulseaudio source sampling rate: 44100 Hz. We will use the same rate.
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.395 - PulseEffects - INFO - loading Pulseeffects applications sink...
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.395 - PulseEffects - INFO - Pulseeffects apps sink was successfully loaded
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.396 - PulseEffects - INFO - Pulseeffects apps sink index:21
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.396 - PulseEffects - INFO - Pulseeffects apps sink monitor name: PulseEffects_apps.monitor
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.396 - PulseEffects - INFO - loading Pulseeffects microphone output sink...
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.396 - PulseEffects - INFO - Pulseeffects mic sink was successfully loaded
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.396 - PulseEffects - INFO - Pulseeffects mic sink index:22
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.396 - PulseEffects - INFO - Pulseeffects mic sink monitor name: PulseEffects_mic.monitor
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.410 - PulseEffects - INFO - limiter plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.411 - PulseEffects - INFO - compressor plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.411 - PulseEffects - INFO - reverb plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.411 - PulseEffects - INFO - highpass plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.411 - PulseEffects - INFO - lowpass plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.412 - PulseEffects - INFO - equalizer plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.412 - PulseEffects - INFO - spectrum plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.417 - PulseEffects - INFO - apps: panorama plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.418 - PulseEffects - INFO - apps: exciter plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.418 - PulseEffects - INFO - apps: bass plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.418 - PulseEffects - INFO - apps: output plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.423 - PulseEffects - INFO - limiter plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.423 - PulseEffects - INFO - compressor plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.423 - PulseEffects - INFO - reverb plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.424 - PulseEffects - INFO - highpass plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.424 - PulseEffects - INFO - lowpass plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.424 - PulseEffects - INFO - equalizer plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.424 - PulseEffects - INFO - spectrum plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.731 - PulseEffects - INFO - apps: spectrum plugin was enabled
Dec 12 22:38:01 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: 22:38:01.731 - PulseEffects - INFO - mic: spectrum plugin was enabled
Dec 12 22:38:02 MtOlympus com.github.wwmm.pulseeffects.desktop[17129]: Assertion 'q->front' failed at pulsecore/queue.c:81, function pa_queue_push(). Aborting.

**Comment by therealcyber5** [comment]
OKAY - this is totally on my end. If I switch users - all of the logging goes away and things seem to work as expected. Both user accounts are SUDO capable - and I did not add any special logging commands to the original account. Im not sure why it acts it differently. This is a fresh install of Ubuntu 17.10 on a Ryzen 5 1600 processor.  I appreciate the efforts of mikhailnov and wwmm to help a newbie out! There just seems to be an issue with that one profile so I'm going to abandon it and perhaps reinstall the OS for good measure.

**Comment by wwmm** [comment]
Deleting the folder `~/.config/PulseEffects` would only remove the users presets. The other settings are stored in dconf keys that can be changed/reset in Dconf. They could also be reset using the reset button in the main menu.

The line `gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed` was not a harmless warning but a problem. I don't know what could be causing the number of channels to be wrongly set but if changing the user solved the problem it is possible that you had a corrupted gstreamer cache `~/.cache/gstreamer-1.0` or a bad configured pulseaudio configuration file `~/.config/pulse`.

I will close this issue. Feel free to open another in case of additional problems.

**Comment by TheAifam5** [comment]
i have also that problem after changing latency time to 4...

**Comment by TheAifam5** [comment]
setting back to 10 (really fast) repairs problem with `ERROR:gstspectrum.c:991:gst_spectrum_transform_ip: assertion failed: (size == 0)`

**Comment by TheAifam5** [comment]
latency time 7 throws `gst_level_transform_ip: assertion 'num_int_samples % channels == 0' failed`

**Comment by wwmm** [comment]
Which sampling rate the default pulseaudio output device is using? If I am not mistaken de possible latency values are sampling rate dependent. 44.1 kHz has fewer allowed values than 48 kHz for example. There is not much I can do about that. It is a limitation in gstreamer or pulseaudio.

**Comment by TheAifam5** [comment]
yep, 48kHz.. :) would be nice to integrate those "limitations"

**Comment by wwmm** [comment]
It would :-) but this is something that only pulseaudio or gstreamer developers would know how to do. 

I tested here and with 44.1 kHz the only values that work for me are 10 and 1.  If I use 48 kHz any value works. Are you sure pulseaudio output sink is using 48 kHz? Is this the value printed by Pulseeffects when you run it from command line?

**Comment by wwmm** [comment]
You can reset this value in dconf editor

**Comment by wwmm** [comment]
![screenshot from 2017-12-13 22-21-53](https://user-images.githubusercontent.com/16225172/33969388-2027f478-e054-11e7-96e6-06ecfea10ad1.png)

**Comment by RyanNerd** [comment]
Please reopen and fix this. Please so that everyone that sets their config to something invalid doesn't need to do a web search to find this page for the solution. Instead prevent users from entering invalid configuration values, or at least display a warning that the invalid config is risky.
