### ISSUE TITLE
No Visualization and a lot of errors

### ISSUE THREAD

**Issue by kolorafa** [wwmm/pulseeffects#14]
PE 1.4.2

ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/PulseEffects/gst.py", line 346, in on_message
    if max(magnitudes) > -100:
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/PulseEffects/gst.py", line 346, in on_message
....

and keeps repeating

**Comment by wwmm** [comment]
Hi

I released a new version that should fix this error.

**Comment by teamosceola** [comment]
I also have no spectrum visualization, but with a different repeating error.

Traceback (most recent call last):
  File "/home/chris/pulseeffects/PulseEffects/gst.py", line 343, in on_message
    magnitudes = msg.get_structure().get_value('magnitude')
TypeError: unknown type GstValueList
...

This is as of:
commit 6fe629e4d5d8100eb29807d80ec5d0b45b267425
Author: wwmm <wellington.melo@cefet-rj.br>
Date:   Sun May 28 17:46:55 2017 -0300

    updated readme image

Thanks!

**Comment by wwmm** [comment]
Hi,

Use version 1.4.1 [https://github.com/wwmm/pulseeffects/archive/v1.4.1.tar.gz](https://github.com/wwmm/pulseeffects/archive/v1.4.1.tar.gz). From version 1.4.3 onwards I moved to gstreamer 1.12. You probably have a lower version in your system. Before Gstreamer 1.12 we needed a hack to get spectrum magnitudes from Python. the type GstValueList was not exposed in gst-python api. Gstreamer developers added the missing types in Gstreamer 1.12

**Comment by kolorafa** [comment]
1.4.4 - still the same error BUT

I see that i don't have visuals if i use 
$ pactl load-module module-echo-cancel
and set the default output to that module

If i just switch default back to soundcard it works.


While switched to soundcard:
<pre>
$ pulseeffects 
21:24:30.73 - PulseEffects - INFO - pulseaudio context started
21:24:30.74 - PulseEffects - INFO - pulseaudio version: 10.0
21:24:30.74 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo.echo-cancel
21:24:30.74 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo
21:24:30.74 - PulseEffects - INFO - default pulseaudio sink sampling rate: 44100 Hz. We will use the same rate.
21:24:30.74 - PulseEffects - INFO - loading Pulseeffects sink...
21:24:30.75 - PulseEffects - INFO - sink idx: 33
21:24:30.75 - PulseEffects - INFO - Pulseeffects sink was successfully loaded
21:24:30.75 - PulseEffects - INFO - Pulseeffects sink monitor name: PulseEffects.monitor. We will process audio from this source.
</pre>

While switched to echo cancelled soundcard:
<pre>
$ pulseeffects 
21:26:14.206 - PulseEffects - INFO - pulseaudio context started
21:26:14.206 - PulseEffects - INFO - pulseaudio version: 10.0
21:26:14.206 - PulseEffects - INFO - default pulseaudio source: alsa_input.pci-0000_00_1b.0.analog-stereo.echo-cancel
21:26:14.206 - PulseEffects - INFO - default pulseaudio sink: alsa_output.pci-0000_00_1b.0.analog-stereo.echo-cancel
21:26:14.206 - PulseEffects - INFO - default pulseaudio sink sampling rate: 32000 Hz. We will use the same rate.
21:26:14.206 - PulseEffects - INFO - loading Pulseeffects sink...
21:26:14.207 - PulseEffects - INFO - sink idx: 34
21:26:14.207 - PulseEffects - INFO - Pulseeffects sink was successfully loaded
21:26:14.207 - PulseEffects - INFO - Pulseeffects sink monitor name: PulseEffects.monitor. We will process audio from this source.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/PulseEffects/gst.py", line 263, in media_probe
    element = next(i for i in self.spectrum_freqs if i >
StopIteration
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/PulseEffects/gst.py", line 348, in on_message
    max_mag = max(magnitudes)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/PulseEffects/gst.py", line 348, in on_message
    max_mag = max(magnitudes)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/PulseEffects/gst.py", line 348, in on_message
    max_mag = max(magnitudes)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/PulseEffects/gst.py", line 348, in on_message
    max_mag = max(magnitudes)
ValueError: max() arg is an empty sequence
Traceback (most recent call last):
.....
</pre>

**Comment by wwmm** [comment]
I was able to reproduce the problem with module-echo-cancel. Its lower sampling rate(32000 Hz) is triggering this bug. If I have the time I will release a new version fixing this in 1 or 2 days.

**Comment by wwmm** [comment]
I released version 1.4.5. It fixes the problem with module-echo-cancel in my system.
